/**
 * DOCUMENT GENERATION — deterministic, no LLM, idempotent.
 *
 * Same playbook.json always produces byte-identical markdown. The renderer is
 * where the trust model becomes visible to a human reader: facts, assumptions
 * and estimates are rendered in separate, labelled sections so nobody can
 * mistake a projection for a measurement.
 */

import { AGENT_IDS, AGENT_TITLES, agentDocNumber } from './util.mjs';

const DISCLAIMER = [
  '> **Not legal, tax, security, financial or engineering advice.**',
  '> This document is generated by AI agents from a defined source pack.',
  '> Facts are traceable to listed sources; assumptions and estimates are not',
  '> evidence. Confirm with qualified Indian counsel, a chartered accountant,',
  '> your payment provider and a security professional before acting.',
].join('\n');

function esc(s) {
  return String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
}

function fmtNum(n) {
  if (typeof n !== 'number') return String(n);
  return Number.isInteger(n) ? n.toLocaleString('en-IN') : n.toLocaleString('en-IN', { maximumFractionDigits: 2 });
}

function confidenceBadge(v) {
  if (v >= 0.75) return `HIGH (${v.toFixed(2)})`;
  if (v >= 0.5) return `MODERATE (${v.toFixed(2)})`;
  if (v >= 0.25) return `LOW (${v.toFixed(2)})`;
  return `VERY LOW (${v.toFixed(2)})`;
}

function sourceLine(s) {
  const bits = [`**${s.id}**`, s.publisher, '—', s.title];
  if (s.url) bits.push(`<${s.url}>`);
  bits.push(`_(${s.type}, accessed ${s.accessed_at})_`);
  return '- ' + bits.join(' ');
}

/** One agent document. */
export function renderAgentDoc(entry, playbook) {
  const d = entry.document;
  const L = [];
  const num = agentDocNumber(d.agent.id);

  L.push(`# ${num} · ${entry.title}`, '');
  L.push(DISCLAIMER, '');
  L.push('| | |', '|---|---|');
  L.push(`| **Run** | \`${playbook.run_id}\` |`);
  L.push(`| **Generated** | ${d.generated_at} |`);
  L.push(`| **Model** | \`${d.agent.model}\` |`);
  L.push(`| **Prompt version** | \`${d.agent.version}\` (sha256 \`${d.agent.prompt_sha256.slice(0, 12)}…\`) |`);
  L.push(`| **Input digest** | \`${d.input_digest.slice(0, 16)}…\` |`);
  L.push(`| **Confidence** | ${confidenceBadge(d.confidence.overall)} |`);
  L.push('');

  L.push('## Executive summary', '', d.executive_summary.trim(), '');

  // FACTS
  L.push('## Facts', '');
  if (!(d.facts ?? []).length) {
    L.push('_No sourced facts were produced. Everything below is assumption or estimate._', '');
  } else {
    L.push('Each row is traceable to a source in the register at the end of this document.', '');
    L.push('| ID | Statement | Value | As of | Verification | Sources |');
    L.push('|---|---|---|---|---|---|');
    for (const f of d.facts) {
      const val = f.value == null ? '—' : `${fmtNum(f.value)}${f.unit ? ' ' + f.unit : ''}`;
      L.push(`| ${f.id} | ${esc(f.statement)} | ${esc(val)} | ${f.as_of} | ${f.verification} | ${f.source_ids.join(', ')} |`);
    }
    L.push('');
  }

  // ASSUMPTIONS
  L.push('## Assumptions', '');
  if (!(d.assumptions ?? []).length) {
    L.push('_None declared._', '');
  } else {
    L.push('**These are not facts.** Each one is a belief this analysis rests on.', '');
    L.push('| ID | Assumption | Impact if wrong | How to validate |');
    L.push('|---|---|---|---|');
    for (const a of d.assumptions) {
      L.push(`| ${a.id} | ${esc(a.statement)} | **${a.impact_if_wrong.toUpperCase()}** | ${esc(a.validation_method)} |`);
    }
    L.push('');
    for (const a of d.assumptions) L.push(`- **${a.id} rationale** — ${a.rationale}`);
    L.push('');
  }

  // ESTIMATES
  L.push('## Estimates', '');
  if (!(d.estimates ?? []).length) {
    L.push('_None produced._', '');
  } else {
    L.push('Ranges, not point predictions. `base` is the working number; `low`/`high` bound the uncertainty.', '');
    L.push('| ID | Metric | Low | Base | High | Unit | Method | Rests on |');
    L.push('|---|---|---|---|---|---|---|---|');
    for (const e of d.estimates) {
      L.push(`| ${e.id} | ${esc(e.metric)} | ${fmtNum(e.low)} | **${fmtNum(e.base)}** | ${fmtNum(e.high)} | ${esc(e.unit)} | ${e.method} | ${(e.depends_on ?? []).join(', ') || '—'} |`);
    }
    L.push('');
  }

  // RECOMMENDATIONS
  L.push('## Recommendations', '');
  if (!(d.recommendations ?? []).length) {
    L.push('_None produced._', '');
  } else {
    L.push('| ID | Priority | Action | Owner | Effort | Basis | Review needed |');
    L.push('|---|---|---|---|---|---|---|');
    for (const r of d.recommendations) {
      const rev = r.requires_professional_review ? '**YES**' : 'no';
      L.push(`| ${r.id} | ${r.priority} | ${esc(r.action)} | ${esc(r.owner_role)} | ${r.effort ?? '—'} | ${(r.rationale_ids ?? []).join(', ') || '—'} | ${rev} |`);
    }
    L.push('');
  }

  // RISKS
  L.push('## Risks', '');
  if (!(d.risks ?? []).length) {
    L.push('_None produced._', '');
  } else {
    L.push('| ID | Risk | Category | L | I | Score | Mitigation |');
    L.push('|---|---|---|---|---|---|---|');
    const sorted = [...d.risks].sort((a, b) => b.likelihood * b.impact - a.likelihood * a.impact);
    for (const k of sorted) {
      L.push(`| ${k.id} | ${esc(k.description)} | ${k.category} | ${k.likelihood} | ${k.impact} | **${k.likelihood * k.impact}** | ${esc(k.mitigation)} |`);
    }
    L.push('');
  }

  // DEPENDENCIES
  if ((d.dependencies ?? []).length) {
    L.push('## Dependencies on other agents', '');
    for (const dep of d.dependencies) {
      L.push(`- \`${dep.relationship}\` → **${AGENT_TITLES[dep.agent_id] ?? dep.agent_id}**${dep.note ? ` — ${dep.note}` : ''}`);
    }
    L.push('');
  }

  // COVERAGE
  if (d.coverage?.unanswered_questions?.length) {
    L.push('## Open questions', '');
    for (const q of d.coverage.unanswered_questions) L.push(`- ${q}`);
    L.push('');
  }

  // SOURCES
  L.push('## Sources', '');
  if (!(d.sources ?? []).length) L.push('_None._', '');
  else { for (const s of d.sources) L.push(sourceLine(s)); L.push(''); }

  L.push('---', `_Run \`${playbook.run_id}\` · generated ${playbook.generated_at} · schema ${d.schema_version}_`, '');
  return L.join('\n');
}

/** Combined master document. */
export function renderMaster(playbook) {
  const L = [];
  const t = playbook.totals;

  L.push('# India Launch Playbook', '');
  L.push(`**Run:** \`${playbook.run_id}\`  `);
  L.push(`**Generated:** ${playbook.generated_at}  `);
  L.push(`**Overall confidence:** ${confidenceBadge(playbook.confidence.overall)}`, '');
  L.push(DISCLAIMER, '');

  L.push('## The idea analysed', '');
  L.push('| Field | Value |', '|---|---|');
  L.push(`| Business idea | ${esc(playbook.input.business_idea)} |`);
  L.push(`| Sector | ${esc(playbook.input.sector)} |`);
  L.push(`| Target customer | ${esc(playbook.input.target_customer)} |`);
  L.push(`| Geography | ${esc((playbook.input.geography ?? []).join(', '))} |`);
  L.push(`| Stage | ${esc(playbook.input.stage ?? 'idea')} |`);
  L.push(`| Budget band | ${esc(playbook.input.budget_band ?? 'unknown')} |`);
  L.push('');

  L.push('## What this run contains', '');
  L.push('| Metric | Count |', '|---|---|');
  L.push(`| Agents completed | ${t.agents} / ${t.agents_expected} |`);
  L.push(`| Sourced facts | ${t.facts} |`);
  L.push(`| Declared assumptions | ${t.assumptions} |`);
  L.push(`| Estimates (ranged) | ${t.estimates} |`);
  L.push(`| Recommendations | ${t.recommendations} |`);
  L.push(`| Risks | ${t.risks} |`);
  L.push(`| Distinct sources | ${t.sources} |`);
  L.push(`| Cross-agent conflicts | ${t.conflicts} |`);
  L.push('');
  if (t.agents_missing.length) {
    L.push(`> ⚠️ **Incomplete run.** Missing agents: ${t.agents_missing.join(', ')}.`, '');
  }

  if (playbook.conflicts.length) {
    L.push('## ⚠️ Cross-agent conflicts', '');
    L.push('Detected deterministically. Resolve before relying on affected numbers.', '');
    L.push('| Severity | Type | Detail |', '|---|---|---|');
    for (const c of playbook.conflicts) {
      L.push(`| ${c.severity.toUpperCase()} | ${c.type} | ${esc(c.detail)} |`);
    }
    L.push('');
  } else {
    L.push('## Cross-agent conflicts', '', '_None detected._', '');
  }

  if (playbook.priority_actions.length) {
    L.push('## P0 actions', '');
    L.push('| Agent | ID | Action | Owner | Professional review |', '|---|---|---|---|---|');
    for (const p of playbook.priority_actions) {
      L.push(`| ${p.agent} | ${p.id} | ${esc(p.action)} | ${esc(p.owner_role)} | ${p.requires_professional_review ? '**YES**' : 'no'} |`);
    }
    L.push('');
  }

  if (playbook.top_risks.length) {
    L.push('## Top risks across all agents', '');
    L.push('| Score | Category | Risk | Mitigation | Agent |', '|---|---|---|---|---|');
    for (const k of playbook.top_risks) {
      L.push(`| **${k.score}** | ${k.category} | ${esc(k.description)} | ${esc(k.mitigation)} | ${k.agent} |`);
    }
    L.push('');
  }

  L.push('## Contents', '');
  for (const a of playbook.agents) {
    L.push(`${agentDocNumber(a.id)}. [${a.title}](${agentDocNumber(a.id)}-${a.id.replace(/_/g, '-')}.md) — ` +
           `${a.counts.facts} facts · ${a.counts.assumptions} assumptions · ${a.counts.estimates} estimates`);
  }
  L.push('');
  L.push('- [Assumption register](ASSUMPTIONS.md)');
  L.push('- [Source register](SOURCES.md)');
  L.push('');

  for (const a of playbook.agents) {
    L.push('---', '', `## ${agentDocNumber(a.id)} · ${a.title}`, '');
    L.push(`**Confidence:** ${confidenceBadge(a.confidence.overall)}`, '');
    L.push(a.executive_summary.trim(), '');
    L.push(`→ Full detail: [\`${agentDocNumber(a.id)}-${a.id.replace(/_/g, '-')}.md\`](${agentDocNumber(a.id)}-${a.id.replace(/_/g, '-')}.md)`, '');
  }

  L.push('---', '');
  L.push(`_Generated by the India Launch Playbook pipeline. Run \`${playbook.run_id}\`._`, '');
  return L.join('\n');
}

export function renderAssumptions(playbook) {
  const L = ['# Assumption register', ''];
  L.push(`**Run:** \`${playbook.run_id}\` · **Generated:** ${playbook.generated_at}`, '');
  L.push('Every belief this playbook rests on, deduplicated across agents and ranked', 'by what breaks if it is wrong. Validate the CRITICAL rows first.', '');
  if (!playbook.assumption_register.length) { L.push('_No assumptions declared._', ''); return L.join('\n'); }
  L.push('| Impact | Assumption | How to validate | Asserted by |', '|---|---|---|---|');
  for (const a of playbook.assumption_register) {
    const by = a.asserted_by.map((x) => `${x.agent}:${x.id}`).join(', ');
    L.push(`| **${a.impact_if_wrong.toUpperCase()}** | ${esc(a.statement)} | ${esc(a.validation_method)} | ${by} |`);
  }
  L.push('');
  L.push('## Rationale detail', '');
  for (const a of playbook.assumption_register) {
    L.push(`### ${a.statement}`, '', `- **Impact if wrong:** ${a.impact_if_wrong}`, `- **Rationale:** ${a.rationale}`,
           `- **Validation:** ${a.validation_method}`, `- **Asserted by:** ${a.asserted_by.map((x) => `${x.agent}:${x.id}`).join(', ')}`, '');
  }
  return L.join('\n');
}

export function renderSources(playbook) {
  const L = ['# Source register', ''];
  L.push(`**Run:** \`${playbook.run_id}\` · **Generated:** ${playbook.generated_at}`, '');
  L.push(`Source pack mode: \`${playbook.source_pack_mode}\``, '');
  L.push('Agents could cite only these sources. Anything not supported by one of', 'them was recorded as an assumption or an estimate, never as a fact.', '');
  if (!playbook.source_register.length) { L.push('_No sources._', ''); return L.join('\n'); }

  const byType = new Map();
  for (const s of playbook.source_register) {
    if (!byType.has(s.type)) byType.set(s.type, []);
    byType.get(s.type).push(s);
  }
  for (const [type, items] of [...byType].sort()) {
    L.push(`## ${type}`, '');
    for (const s of items) {
      L.push(sourceLine(s));
      L.push(`  - cited by: ${s.cited_by.map((c) => `${c.agent} (${c.source_id})`).join(', ')}`);
    }
    L.push('');
  }

  const modelOnly = playbook.source_register.filter((s) => s.type === 'model_internal_knowledge');
  if (modelOnly.length) {
    L.push('## ⚠️ Model internal knowledge', '');
    L.push('These carry no external provenance and may never back a fact.', '');
    for (const s of modelOnly) L.push(sourceLine(s));
    L.push('');
  }
  return L.join('\n');
}

export function renderManifest(playbook, files) {
  return {
    schema_version: '1.0.0',
    run_id: playbook.run_id,
    generated_at: playbook.generated_at,
    input_digest: playbook.input_digest,
    source_pack_mode: playbook.source_pack_mode,
    confidence: playbook.confidence,
    totals: playbook.totals,
    agents: playbook.agents.map((a) => ({
      id: a.id, model: a.model, prompt_sha256: a.prompt_sha256,
      generated_at: a.generated_at, counts: a.counts,
    })),
    files: files.map((f) => ({ path: f.path, bytes: f.bytes, sha256: f.sha256 })),
  };
}

export function renderAll(playbook) {
  const out = [];
  for (const a of playbook.agents) {
    out.push({ name: `${agentDocNumber(a.id)}-${a.id.replace(/_/g, '-')}.md`, content: renderAgentDoc(a, playbook) });
  }
  out.push({ name: 'MASTER-PLAYBOOK.md', content: renderMaster(playbook) });
  out.push({ name: 'ASSUMPTIONS.md', content: renderAssumptions(playbook) });
  out.push({ name: 'SOURCES.md', content: renderSources(playbook) });
  return out;
}
